"use client";
import{FormEvent,useCallback,useEffect,useState}from"react";
import{supabase}from"@/lib/supabase/client";
type Customer={id:string;name:string;phone:string|null;email:string|null;active:boolean;last_transaction_at:string|null;points_balance:number;referral_code:string;referred_by:string|null;created_at:string};
type Data={settings:{loyalty_enabled:boolean;points_per_100:number;referral_reward_points:number;customer_auto_archive_months:number};customers:Customer[]};
export function CustomerLoyalty({organizationId,isAdmin}:{organizationId:string;isAdmin:boolean}){const[data,setData]=useState<Data|null>(null);const[showAdd,setShowAdd]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");const load=useCallback(async()=>{setError("");const{data:result,error:e}=await supabase.rpc("get_customer_workspace",{p_organization_id:organizationId});if(e)setError(e.message);else setData(result as Data);},[organizationId]);useEffect(()=>{void load();},[load]);
async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const f=new FormData(event.currentTarget);const{error:e}=await supabase.rpc("create_customer_with_referral",{p_organization_id:organizationId,p_name:String(f.get("name")),p_phone:String(f.get("phone")),p_email:String(f.get("email")),p_referral_code:String(f.get("referralCode"))});if(e)setError(e.message);else{setMessage("Customer created.");setShowAdd(false);await load();}setBusy(false);}
async function setActive(id:string,active:boolean){setBusy(true);setError("");const{error:e}=await supabase.rpc("set_customer_active",{p_customer_id:id,p_active:active});if(e)setError(e.message);else{setMessage(active?"Customer reactivated.":"Customer archived.");await load();}setBusy(false);}
async function settings(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const f=new FormData(event.currentTarget);const{error:e}=await supabase.rpc("update_loyalty_settings",{p_organization_id:organizationId,p_enabled:f.get("enabled")==="on",p_points_per_100:Number(f.get("points")),p_referral_reward_points:Number(f.get("referral")),p_auto_archive_months:Number(f.get("months"))});if(e)setError(e.message);else{setMessage("Customer and loyalty settings saved.");await load();}setBusy(false);}
if(!data&&!error)return <div className="contentLoading">Loading customers…</div>;return <div className="contentStack">{error&&<div className="formError">{error}</div>}{message&&<div className="formSuccess">{message}</div>}<div className="sectionActions"><p>Manage customers, inactivity archiving, referrals, and purchase points.</p><button className="primaryButton compact" onClick={()=>setShowAdd(v=>!v)}>{showAdd?"Cancel":"Add customer"}</button></div>{showAdd&&<form className="inventoryForm" onSubmit={add}><div className="formGrid"><label>Name<input name="name" required/></label><label>Phone<input name="phone"/></label><label>Email<input name="email" type="email"/></label><label>Referral code <small>(optional)</small><input name="referralCode"/></label></div><button className="primaryButton compact" disabled={busy}>Save customer</button></form>}{isAdmin&&data&&<form className="settingsForm loyaltySettings" onSubmit={settings}><div className="controlHeader"><div><h3>Loyalty and referral settings</h3><small>Points are added after completed sales and reversed when sales are voided.</small></div><label className="toggleLabel"><input name="enabled" type="checkbox" defaultChecked={data.settings.loyalty_enabled}/>Enable loyalty</label></div><div className="formGrid"><label>Points per ₱100 spent<input name="points" type="number" min="0" step="0.01" defaultValue={data.settings.points_per_100}/></label><label>Referral reward points<input name="referral" type="number" min="0" step="0.01" defaultValue={data.settings.referral_reward_points}/></label><label>Auto-archive after<input name="months" type="number" min="1" max="120" defaultValue={data.settings.customer_auto_archive_months}/><small>Months without a transaction</small></label></div><button className="primaryButton compact" disabled={busy}>Save settings</button></form>}<div className="tableWrap"><table><thead><tr><th>Customer</th><th>Last purchase</th><th>Points</th><th>Referral code</th><th>Status</th><th>Action</th></tr></thead><tbody>{(data?.customers??[]).map(c=><tr key={c.id}><td><strong>{c.name}</strong><small>{c.phone||c.email||"No contact details"}{c.referred_by?` · Referred by ${c.referred_by}`:""}</small></td><td>{c.last_transaction_at?new Date(c.last_transaction_at).toLocaleDateString():"No purchases"}</td><td>{Number(c.points_balance).toFixed(2)}</td><td><strong>{c.referral_code}</strong></td><td><span className={c.active?"statusPill":"statusPill inactive"}>{c.active?"Active":"Archived"}</span></td><td><button className="tableAction" disabled={busy} onClick={()=>void setActive(c.id,!c.active)}>{c.active?"Archive":"Reactivate"}</button></td></tr>)}</tbody></table></div></div>}
