"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase/client";

type Product={id:string;name:string;sku:string;barcode:string|null;unit:string;price:number;quantity:number};
type Sale={id:string;receipt_number:string;status:string;total:number;payment_method:string;cashier_name:string|null;created_at:string;items:Array<{product_name:string;sku:string;quantity:number;unit_price:number;line_total:number}>};
type PosData={products:Product[];sales:Sale[]};
type CartItem={product:Product;quantity:number};

export function PointOfSale({organizationId,branchId,branchName,canVoid}:{organizationId:string;branchId:string;branchName:string;canVoid:boolean}){
  const[data,setData]=useState<PosData|null>(null);const[cart,setCart]=useState<CartItem[]>([]);const[query,setQuery]=useState("");const[view,setView]=useState<"pos"|"history">("pos");const[payment,setPayment]=useState("cash");const[tendered,setTendered]=useState("");const[receipt,setReceipt]=useState<{receipt_number:string;total:number;change_amount:number}|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  const load=useCallback(async()=>{if(!branchId)return;setLoading(true);setError("");const{data:result,error:e}=await supabase.rpc("get_pos_workspace",{p_organization_id:organizationId,p_branch_id:branchId});if(e)setError(e.message);else setData(result as PosData);setLoading(false);},[organizationId,branchId]);useEffect(()=>{setCart([]);void load();},[load]);
  const products=useMemo(()=>{const q=query.toLowerCase().trim();return(data?.products??[]).filter(p=>!q||p.name.toLowerCase().includes(q)||p.sku.toLowerCase().includes(q)||p.barcode?.includes(q));},[data,query]);
  const total=cart.reduce((sum,item)=>sum+Number(item.product.price)*item.quantity,0);
  function add(product:Product){if(Number(product.quantity)<=0)return;setCart(items=>{const found=items.find(i=>i.product.id===product.id);return found?items.map(i=>i.product.id===product.id?{...i,quantity:Math.min(i.quantity+1,Number(product.quantity))}:i):[...items,{product,quantity:1}]});setQuery("");}
  function quantity(id:string,next:number){setCart(items=>items.map(i=>i.product.id===id?{...i,quantity:Math.max(1,Math.min(next,Number(i.product.quantity)))}:i));}
  async function checkout(){setBusy(true);setError("");const{data:result,error:e}=await supabase.rpc("create_pos_sale",{p_organization_id:organizationId,p_branch_id:branchId,p_items:cart.map(i=>({product_id:i.product.id,quantity:i.quantity})),p_payment_method:payment,p_amount_tendered:payment==="cash"?Number(tendered):total,p_idempotency_key:crypto.randomUUID()});if(e)setError(e.message);else{setReceipt(result);setCart([]);setTendered("");await load();}setBusy(false);}
  async function voidSale(id:string){const reason=window.prompt("Enter the reason for voiding this sale:");if(!reason)return;setBusy(true);setError("");const{error:e}=await supabase.rpc("void_pos_sale",{p_sale_id:id,p_reason:reason});if(e)setError(e.message);else await load();setBusy(false);}
  if(loading)return <div className="contentLoading">Loading Point of Sale…</div>;
  return <div className="contentStack posWorkspace">{error&&<div className="formError">{error}</div>}<div className="sectionActions"><div className="modeTabs posTabs"><button className={view==="pos"?"active":""} onClick={()=>setView("pos")}>Point of Sale</button><button className={view==="history"?"active":""} onClick={()=>setView("history")}>Sales history</button></div><strong>{branchName}</strong></div>
  {view==="pos"?<div className="posGrid"><section className="productPicker"><input className="productSearch" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search product, SKU, or scan barcode" autoFocus/ ><div className="productTiles">{products.map(p=><button key={p.id} disabled={Number(p.quantity)<=0} onClick={()=>add(p)}><strong>{p.name}</strong><span>{p.sku}</span><b>₱{Number(p.price).toFixed(2)}</b><small>{p.quantity} {p.unit} available</small></button>)}</div></section><aside className="cartPanel"><h2>Current sale</h2><div className="cartItems">{cart.length===0?<p className="mutedText">Add products to begin a sale.</p>:cart.map(i=><div className="cartItem" key={i.product.id}><div><strong>{i.product.name}</strong><small>₱{Number(i.product.price).toFixed(2)} each</small></div><input type="number" min="1" max={i.product.quantity} value={i.quantity} onChange={e=>quantity(i.product.id,Number(e.target.value))}/><b>₱{(Number(i.product.price)*i.quantity).toFixed(2)}</b><button onClick={()=>setCart(items=>items.filter(x=>x.product.id!==i.product.id))}>×</button></div>)}</div><div className="cartTotal"><span>Total</span><strong>₱{total.toFixed(2)}</strong></div><label>Payment method<select value={payment} onChange={e=>setPayment(e.target.value)}><option value="cash">Cash</option><option value="card">Card</option><option value="ewallet">E-wallet</option><option value="other">Other</option></select></label>{payment==="cash"&&<label>Amount tendered<input type="number" min={total} step="0.01" value={tendered} onChange={e=>setTendered(e.target.value)}/></label>}<button className="primaryButton" disabled={busy||cart.length===0||(payment==="cash"&&Number(tendered)<total)} onClick={()=>void checkout()}>{busy?"Processing…":"Complete sale"}</button></aside></div>:<div className="tableWrap"><table><thead><tr><th>Receipt</th><th>Date</th><th>Cashier</th><th>Payment</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody>{(data?.sales??[]).map(s=><tr key={s.id}><td><strong>{s.receipt_number}</strong><small>{s.items?.length??0} item lines</small></td><td>{new Date(s.created_at).toLocaleString()}</td><td>{s.cashier_name||"Staff"}</td><td className="capitalize">{s.payment_method}</td><td>₱{Number(s.total).toFixed(2)}</td><td><span className={s.status==="completed"?"statusPill":"statusPill inactive"}>{s.status}</span></td><td>{canVoid&&s.status==="completed"&&<button className="tableAction danger" disabled={busy} onClick={()=>void voidSale(s.id)}>Void</button>}</td></tr>)}</tbody></table></div>}
  {receipt&&<div className="receiptOverlay"><section className="receiptCard"><div className="receiptPrint"><h2>RetailFlow</h2><p>{branchName}</p><hr/><strong>{receipt.receipt_number}</strong><div><span>Total</span><b>₱{Number(receipt.total).toFixed(2)}</b></div><div><span>Change</span><b>₱{Number(receipt.change_amount).toFixed(2)}</b></div><hr/><p>Thank you for your purchase.</p></div><div className="rowActions"><button className="secondaryButton" onClick={()=>setReceipt(null)}>Close</button><button className="primaryButton compact" onClick={()=>window.print()}>Print receipt</button></div></section></div>}
  </div>;
}
