"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase/client";

type PurchaseItem={id:string;product_id:string;product_name:string;sku:string;quantity_ordered:number;quantity_received:number;unit_cost:number;tracks_expiration:boolean;default_shelf_life_days:number|null};
type PurchaseOrder={id:string;po_number:string;status:string;supplier_name:string;ordered_at:string;notes:string|null;items:PurchaseItem[]};
type Data={suppliers:Array<{id:string;name:string;contact_name:string|null}>;products:Array<{id:string;name:string;sku:string;quantity:number;threshold:number;tracks_expiration:boolean;default_shelf_life_days:number|null}>;reorder_suggestions:Array<{product_id:string;name:string;sku:string;quantity:number;threshold:number;suggested_quantity:number}>;purchase_orders:PurchaseOrder[]};

export function PurchasingWorkspace({organizationId,branchId,expirationEnabled}:{organizationId:string;branchId:string;expirationEnabled:boolean}){
  const[data,setData]=useState<Data|null>(null);const[panel,setPanel]=useState<""|"supplier"|"po"|"receive">("");const[selectedOrder,setSelectedOrder]=useState<PurchaseOrder|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
  const load=useCallback(async()=>{const{data:result,error:loadError}=await supabase.rpc("get_purchasing_workspace",{p_organization_id:organizationId,p_branch_id:branchId});if(loadError)setError(loadError.message);else setData(result as Data);},[organizationId,branchId]);
  useEffect(()=>{void load();},[load]);
  async function supplier(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);const{error:saveError}=await supabase.rpc("create_supplier",{p_organization_id:organizationId,p_name:String(form.get("name")),p_contact_name:String(form.get("contact")),p_email:String(form.get("email")),p_phone:String(form.get("phone")),p_address:String(form.get("address"))});if(saveError)setError(saveError.message);else{setMessage("Supplier created.");setPanel("");await load();}setBusy(false);}
  async function createOrder(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);const{error:saveError}=await supabase.rpc("create_purchase_order",{p_organization_id:organizationId,p_branch_id:branchId,p_supplier_id:String(form.get("supplier")),p_items:[{product_id:String(form.get("product")),quantity:Number(form.get("quantity")),unit_cost:Number(form.get("cost"))}],p_notes:String(form.get("notes"))});if(saveError)setError(saveError.message);else{setMessage("Purchase order created.");setPanel("");await load();}setBusy(false);}
  function openReceive(order:PurchaseOrder){setSelectedOrder(order);setPanel("receive");setError("");setMessage("");}
  async function receive(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selectedOrder)return;setBusy(true);setError("");const form=new FormData(event.currentTarget);const receipts=selectedOrder.items.filter(item=>Number(item.quantity_received)<Number(item.quantity_ordered)).map(item=>({item_id:item.id,quantity:Number(form.get(`quantity-${item.id}`)),batch_number:String(form.get(`batch-${item.id}`)??""),manufacture_date:String(form.get(`manufactured-${item.id}`)??""),expiration_date:String(form.get(`expiration-${item.id}`)??"")}));const{error:receiveError}=await supabase.rpc("receive_purchase_order",{p_purchase_order_id:selectedOrder.id,p_receipts:receipts});if(receiveError)setError(receiveError.message);else{setMessage(`${selectedOrder.po_number} received into inventory.`);setPanel("");setSelectedOrder(null);await load();}setBusy(false);}
  return <div className="contentStack">{error&&<div className="formError">{error}</div>}{message&&<div className="formSuccess">{message}</div>}<div className="sectionActions"><p>Manage suppliers, reorder low stock, and receive purchases.</p><div className="rowActions"><button className="secondaryButton" onClick={()=>setPanel(panel==="supplier"?"":"supplier")}>Add supplier</button><button className="primaryButton compact" onClick={()=>setPanel(panel==="po"?"":"po")}>Create purchase order</button></div></div>
    {panel==="supplier"&&<form className="inventoryForm" onSubmit={supplier}><div className="formGrid"><label>Supplier name<input name="name" required/></label><label>Contact<input name="contact"/></label><label>Email<input name="email" type="email"/></label><label>Phone<input name="phone"/></label><label className="fullWidth">Address<input name="address"/></label></div><button className="primaryButton compact" disabled={busy}>Save supplier</button></form>}
    {panel==="po"&&<form className="inventoryForm" onSubmit={createOrder}><div className="formGrid"><label>Supplier<select name="supplier" required>{data?.suppliers.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Product<select name="product" required>{data?.products.map(item=><option key={item.id} value={item.id}>{item.name} ({item.sku})</option>)}</select></label><label>Quantity<input name="quantity" type="number" min=".001" step=".001" required/></label><label>Unit cost<input name="cost" type="number" min="0" step=".01" required/></label><label className="fullWidth">Notes<input name="notes"/></label></div><button className="primaryButton compact" disabled={busy}>Create order</button></form>}
    {panel==="receive"&&selectedOrder&&<form className="inventoryForm purchaseReceiptForm" onSubmit={receive}><div className="sectionActions"><div><h3>Receive {selectedOrder.po_number}</h3><p>Record received quantities{expirationEnabled?", batches, and expiration dates":""}.</p></div><button type="button" className="secondaryButton" onClick={()=>{setPanel("");setSelectedOrder(null);}}>Cancel</button></div>{selectedOrder.items.filter(item=>Number(item.quantity_received)<Number(item.quantity_ordered)).map(item=>{const outstanding=Number(item.quantity_ordered)-Number(item.quantity_received);const suggestedExpiry=item.default_shelf_life_days?futureDate(item.default_shelf_life_days):"";return <fieldset key={item.id}><legend>{item.product_name} · {item.sku}</legend><div className="formGrid"><label>Quantity<input name={`quantity-${item.id}`} type="number" min=".001" max={outstanding} step=".001" defaultValue={outstanding} required/></label>{expirationEnabled&&item.tracks_expiration&&<><label>Batch / lot number<input name={`batch-${item.id}`} required/></label><label>Manufacture date<input name={`manufactured-${item.id}`} type="date"/></label><label>Expiration date<input name={`expiration-${item.id}`} type="date" defaultValue={suggestedExpiry} required/></label></>}</div></fieldset>})}<button className="primaryButton compact" disabled={busy}>{busy?"Receiving…":"Receive inventory"}</button></form>}
    <section className="adminCard"><div className="sectionActions"><div><h2>Reorder suggestions</h2><p>Products at or below their branch threshold.</p></div></div><div className="tableWrap"><table><thead><tr><th>Product</th><th>On hand</th><th>Threshold</th><th>Suggested</th></tr></thead><tbody>{(data?.reorder_suggestions??[]).map(item=><tr key={item.product_id}><td><strong>{item.name}</strong><small>{item.sku}</small></td><td>{item.quantity}</td><td>{item.threshold}</td><td>{item.suggested_quantity}</td></tr>)}</tbody></table></div></section>
    <section className="adminCard"><div className="sectionActions"><div><h2>Purchase orders</h2><p>Receive outstanding quantities directly into branch inventory.</p></div></div><div className="tableWrap"><table><thead><tr><th>PO</th><th>Supplier</th><th>Items</th><th>Status</th><th>Action</th></tr></thead><tbody>{(data?.purchase_orders??[]).map(order=><tr key={order.id}><td><strong>{order.po_number}</strong><small>{new Date(order.ordered_at).toLocaleDateString()}</small></td><td>{order.supplier_name}</td><td>{order.items.map(item=>`${item.product_name}: ${item.quantity_received}/${item.quantity_ordered}`).join(", ")}</td><td><span className={order.status==="received"?"statusPill":"statusPill warning"}>{order.status.replace("_"," ")}</span></td><td>{!["received","cancelled"].includes(order.status)&&<button className="tableAction" disabled={busy} onClick={()=>openReceive(order)}>Receive</button>}</td></tr>)}</tbody></table></div></section>
  </div>;
}

function futureDate(days:number){const date=new Date();date.setDate(date.getDate()+days);return date.toISOString().slice(0,10);}
