begin;
create table public.stock_transfers(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,source_branch_id uuid not null references public.branches(id),destination_branch_id uuid not null references public.branches(id),transfer_number text not null,status text not null default 'dispatched' check(status in('dispatched','received','cancelled')),notes text,created_by uuid not null references public.profiles(id),received_by uuid references public.profiles(id),created_at timestamptz not null default now(),received_at timestamptz,check(source_branch_id<>destination_branch_id),unique(organization_id,transfer_number));
create table public.stock_transfer_items(id uuid primary key default gen_random_uuid(),transfer_id uuid not null references public.stock_transfers(id) on delete cascade,product_id uuid not null references public.products(id),quantity numeric(14,3) not null check(quantity>0));
create table public.stocktakes(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid not null references public.branches(id),stocktake_number text not null,status text not null default 'open' check(status in('open','completed','cancelled')),created_by uuid not null references public.profiles(id),completed_by uuid references public.profiles(id),created_at timestamptz not null default now(),completed_at timestamptz,unique(organization_id,stocktake_number));
create table public.stocktake_items(id uuid primary key default gen_random_uuid(),stocktake_id uuid not null references public.stocktakes(id) on delete cascade,product_id uuid not null references public.products(id),expected_quantity numeric(14,3) not null,counted_quantity numeric(14,3));
create table public.inventory_disposals(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid not null references public.branches(id),product_id uuid not null references public.products(id),quantity numeric(14,3) not null check(quantity>0),reason text not null,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
alter table public.stock_transfers enable row level security;alter table public.stock_transfer_items enable row level security;alter table public.stocktakes enable row level security;alter table public.stocktake_items enable row level security;alter table public.inventory_disposals enable row level security;
create policy transfers_read on public.stock_transfers for select to authenticated using(public.current_user_belongs_to_organization(organization_id) or public.current_user_is_platform_administrator());
create policy transfer_items_read on public.stock_transfer_items for select to authenticated using(exists(select 1 from public.stock_transfers t where t.id=transfer_id and(public.current_user_belongs_to_organization(t.organization_id) or public.current_user_is_platform_administrator())));
create policy stocktakes_read on public.stocktakes for select to authenticated using(public.current_user_belongs_to_organization(organization_id) or public.current_user_is_platform_administrator());
create policy stocktake_items_read on public.stocktake_items for select to authenticated using(exists(select 1 from public.stocktakes s where s.id=stocktake_id and(public.current_user_belongs_to_organization(s.organization_id) or public.current_user_is_platform_administrator())));
create policy disposals_read on public.inventory_disposals for select to authenticated using(public.current_user_belongs_to_organization(organization_id) or public.current_user_is_platform_administrator());

create or replace function public.get_inventory_operations(p_organization_id uuid)
returns jsonb language plpgsql stable security definer set search_path=public as $$ begin perform public.require_inventory_access(p_organization_id);return jsonb_build_object(
'transfers',coalesce((select jsonb_agg(jsonb_build_object('id',t.id,'transfer_number',t.transfer_number,'source',sb.name,'destination',db.name,'status',t.status,'created_at',t.created_at,'items',(select jsonb_agg(jsonb_build_object('product_name',p.name,'quantity',i.quantity)) from public.stock_transfer_items i join public.products p on p.id=i.product_id where i.transfer_id=t.id)) order by t.created_at desc) from public.stock_transfers t join public.branches sb on sb.id=t.source_branch_id join public.branches db on db.id=t.destination_branch_id where t.organization_id=p_organization_id),'[]'::jsonb),
'stocktakes',coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'stocktake_number',s.stocktake_number,'branch_name',b.name,'status',s.status,'created_at',s.created_at,'items',(select jsonb_agg(jsonb_build_object('id',i.id,'product_name',p.name,'expected_quantity',i.expected_quantity,'counted_quantity',i.counted_quantity)) from public.stocktake_items i join public.products p on p.id=i.product_id where i.stocktake_id=s.id)) order by s.created_at desc) from public.stocktakes s join public.branches b on b.id=s.branch_id where s.organization_id=p_organization_id),'[]'::jsonb),
'disposals',coalesce((select jsonb_agg(jsonb_build_object('id',d.id,'branch_name',b.name,'product_name',p.name,'quantity',d.quantity,'reason',d.reason,'created_at',d.created_at) order by d.created_at desc) from public.inventory_disposals d join public.branches b on b.id=d.branch_id join public.products p on p.id=d.product_id where d.organization_id=p_organization_id),'[]'::jsonb));end;$$;

create or replace function public.create_stock_transfer(p_organization_id uuid,p_source uuid,p_destination uuid,p_product uuid,p_quantity numeric,p_notes text)
returns uuid language plpgsql security definer set search_path=public as $$ declare new_id uuid;new_qty numeric;num text;begin if not public.current_user_can_manage_inventory(p_organization_id) then raise exception 'Inventory manager access required';end if;if p_source=p_destination or not exists(select 1 from public.branches where id=p_source and organization_id=p_organization_id) or not exists(select 1 from public.branches where id=p_destination and organization_id=p_organization_id) then raise exception 'Invalid transfer branches';end if;update public.branch_products set quantity=quantity-p_quantity,updated_at=now() where branch_id=p_source and product_id=p_product and quantity>=p_quantity returning quantity into new_qty;if new_qty is null then raise exception 'Insufficient source stock';end if;num:='TR-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));insert into public.stock_transfers(organization_id,source_branch_id,destination_branch_id,transfer_number,notes,created_by)values(p_organization_id,p_source,p_destination,num,nullif(trim(p_notes),''),auth.uid())returning id into new_id;insert into public.stock_transfer_items(transfer_id,product_id,quantity)values(new_id,p_product,p_quantity);insert into public.inventory_movements(organization_id,branch_id,product_id,movement_type,quantity_delta,quantity_after,reason,created_by)values(p_organization_id,p_source,p_product,'transfer_out',-p_quantity,new_qty,num,auth.uid());return new_id;end;$$;
create or replace function public.receive_stock_transfer(p_transfer_id uuid)
returns void language plpgsql security definer set search_path=public as $$ declare t public.stock_transfers;i record;new_qty numeric;begin select * into t from public.stock_transfers where id=p_transfer_id for update;if t.id is null or t.status<>'dispatched' or not public.current_user_can_manage_inventory(t.organization_id) then raise exception 'Transfer cannot be received';end if;for i in select * from public.stock_transfer_items where transfer_id=t.id loop insert into public.branch_products(branch_id,product_id,quantity,selling_price,low_stock_threshold)select t.destination_branch_id,i.product_id,i.quantity,coalesce((select selling_price from public.branch_products where branch_id=t.source_branch_id and product_id=i.product_id),0),coalesce((select low_stock_threshold from public.branch_products where branch_id=t.source_branch_id and product_id=i.product_id),0)on conflict(branch_id,product_id)do update set quantity=public.branch_products.quantity+excluded.quantity,updated_at=now() returning quantity into new_qty;insert into public.inventory_movements(organization_id,branch_id,product_id,movement_type,quantity_delta,quantity_after,reason,created_by)values(t.organization_id,t.destination_branch_id,i.product_id,'transfer_in',i.quantity,new_qty,t.transfer_number,auth.uid());end loop;update public.stock_transfers set status='received',received_by=auth.uid(),received_at=now()where id=t.id;end;$$;
create or replace function public.start_stocktake(p_organization_id uuid,p_branch_id uuid)
returns uuid language plpgsql security definer set search_path=public as $$ declare new_id uuid;num text;begin if not public.current_user_can_manage_inventory(p_organization_id)then raise exception 'Inventory manager access required';end if;if exists(select 1 from public.stocktakes where branch_id=p_branch_id and status='open')then raise exception 'This branch already has an open stocktake';end if;num:='ST-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));insert into public.stocktakes(organization_id,branch_id,stocktake_number,created_by)values(p_organization_id,p_branch_id,num,auth.uid())returning id into new_id;insert into public.stocktake_items(stocktake_id,product_id,expected_quantity)select new_id,product_id,quantity from public.branch_products where branch_id=p_branch_id and active;return new_id;end;$$;
create or replace function public.complete_stocktake(p_stocktake_id uuid,p_counts jsonb)
returns void language plpgsql security definer set search_path=public as $$ declare s public.stocktakes;c jsonb;line public.stocktake_items;delta numeric;begin select * into s from public.stocktakes where id=p_stocktake_id for update;if s.id is null or s.status<>'open' or not public.current_user_can_manage_inventory(s.organization_id)then raise exception 'Stocktake cannot be completed';end if;for c in select * from jsonb_array_elements(p_counts)loop select * into line from public.stocktake_items where id=(c->>'item_id')::uuid and stocktake_id=s.id;delta:=(c->>'counted')::numeric-line.expected_quantity;update public.stocktake_items set counted_quantity=(c->>'counted')::numeric where id=line.id;update public.branch_products set quantity=(c->>'counted')::numeric,updated_at=now()where branch_id=s.branch_id and product_id=line.product_id;if delta<>0 then insert into public.inventory_movements(organization_id,branch_id,product_id,movement_type,quantity_delta,quantity_after,reason,created_by)values(s.organization_id,s.branch_id,line.product_id,'stocktake',delta,(c->>'counted')::numeric,s.stocktake_number,auth.uid());end if;end loop;update public.stocktakes set status='completed',completed_by=auth.uid(),completed_at=now()where id=s.id;end;$$;
create or replace function public.dispose_inventory(p_organization_id uuid,p_branch_id uuid,p_product_id uuid,p_quantity numeric,p_reason text)
returns uuid language plpgsql security definer set search_path=public as $$ declare new_id uuid;new_qty numeric;begin if not public.current_user_can_manage_inventory(p_organization_id)then raise exception 'Inventory manager access required';end if;if nullif(trim(p_reason),'')is null then raise exception 'Disposal reason is required';end if;update public.branch_products set quantity=quantity-p_quantity,updated_at=now()where branch_id=p_branch_id and product_id=p_product_id and quantity>=p_quantity returning quantity into new_qty;if new_qty is null then raise exception 'Insufficient stock';end if;insert into public.inventory_disposals(organization_id,branch_id,product_id,quantity,reason,created_by)values(p_organization_id,p_branch_id,p_product_id,p_quantity,trim(p_reason),auth.uid())returning id into new_id;insert into public.inventory_movements(organization_id,branch_id,product_id,movement_type,quantity_delta,quantity_after,reason,created_by)values(p_organization_id,p_branch_id,p_product_id,'disposal',-p_quantity,new_qty,trim(p_reason),auth.uid());return new_id;end;$$;
revoke all on function public.get_inventory_operations(uuid),public.create_stock_transfer(uuid,uuid,uuid,uuid,numeric,text),public.receive_stock_transfer(uuid),public.start_stocktake(uuid,uuid),public.complete_stocktake(uuid,jsonb),public.dispose_inventory(uuid,uuid,uuid,numeric,text) from public;
grant execute on function public.get_inventory_operations(uuid),public.create_stock_transfer(uuid,uuid,uuid,uuid,numeric,text),public.receive_stock_transfer(uuid),public.start_stocktake(uuid,uuid),public.complete_stocktake(uuid,jsonb),public.dispose_inventory(uuid,uuid,uuid,numeric,text) to authenticated;
commit;
